
SYS AS SYSDBA
7530159

ALTER SESSION SET CONTAINER = XEPDB1;


CREATE USER MANAGER IDENTIFIED BY "123"; 
GRANT CREATE SESSION, CREATE USER, ALTER USER, DROP USER TO MANAGER;
ALTER USER MANAGER QUOTA UNLIMITED ON USERS;


sqlplus MANAGER/"123"@localhost:1521/XEPDB1


CREATE USER USER1 IDENTIFIED BY "u1";
CREATE USER USER2 IDENTIFIED BY "u2";

GRANT CREATE SESSION TO USER1;
GRANT CREATE SESSION TO USER2;


